name: build-workflow

on:
  release:
    types: [published]

jobs:
  fetch-tag:
    if: github.event.release.target_commitish == 'main' || github.event.release.target_commitish == 'dev'
    name : Get release tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building release tag
        id: latest_tag
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    outputs:
      release_tag: ${{steps.latest_tag.outputs.tag}}

  get-branch:
    name: 'get-branch'
    runs-on: ubuntu-latest
    steps:
    - run: echo "::set-output name=branch::$(echo ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}})"
      id: current_branch
    outputs:
        release_branch: ${{steps.current_branch.outputs.branch}}

  frontend-img-build:
    name: 'Building frontend docker images'
    runs-on: ubuntu-latest
    needs: [fetch-tag]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: configure the ecr used
        env:
          IMAGE_TAG: ${{needs.get-branch.outputs.release_branch }}
        run: |
          if $IMAGE_TAG == 'main'; then
            echo "ECR_REPO=mcd-discount-prod" >> $GITHUB_ENV
          else
            echo "ECR_REPO=mcd-discount-staging" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v2
      - name: Pushing mcd-discount-frontend image to ECR
        env:
          ECR_REGISTRY: 059014103288.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: ${{ env.ECR_REPO }}-frontend
          IMAGE_TAG: ${{needs.fetch-tag.outputs.release_tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f env/docker_mcdui/Dockerfile .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY


  backend-img-build:
    name: 'Building backend docker images'
    runs-on: ubuntu-latest
    needs: [fetch-tag]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: configure the ecr used
        env:
          IMAGE_TAG: ${{needs.get-branch.outputs.release_branch }}
        run: |
          if $IMAGE_TAG == 'main'; then
            echo "ECR_REPO=mcd-discount-prod" >> $GITHUB_ENV
          else
            echo "ECR_REPO=mcd-discount-staging" >> $GITHUB_ENV
          fi


      - uses: actions/checkout@v2
      - name: Pushing mcd-discount-backend image to ECR
        env:
          ECR_REGISTRY: 059014103288.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: ${{ env.ECR_REPO }}-backend
          IMAGE_TAG: ${{needs.fetch-tag.outputs.release_tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f env/docker_mcdapi/Dockerfile .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
