name: final workflow by merge
on:
  pull_request:
    branches: [dev*, release, uat, qa, dev*]
    types : [closed]
  push:
    branches: [dev*]
    
jobs:  
  tag-release:
    if: github.event.pull_request.merged == true
    name: 'tag-release'
    runs-on: ubuntu-latest
    steps:
    - name: version
      run: echo "::set-output name=branch::$(echo ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}})"
      id: release_tag
    outputs:
        release_tag: ${{steps.release_tag.outputs.branch}}

  build-docker-backend:
    name: 'Building the backend docker image'
    runs-on: ubuntu-latest
    needs: [tag-release]
    steps:
      - uses: actions/checkout@v2
      - name: Building and tagging the backend docker image
        env:
          IMAGE_TAG: ${{needs.tag-release.outputs.release_tag }}
        run: |
          docker build -t mcdapi:$IMAGE_TAG -f env/docker_mcdapi/Dockerfile .

  build-docker-frontend:
    name: 'Building the frontend docker image'
    runs-on: ubuntu-latest
    needs: [tag-release]
    steps:
      - uses: actions/checkout@v2
      - name: Building and tagging the frontend docker image
        env:
          IMAGE_TAG: ${{needs.tag-release.outputs.release_tag }}
        run: |
          docker build -t mcdui:$IMAGE_TAG -f env/docker_mcdui/Dockerfile .
