name: manual release workflow

on:
  release:
    branches: [main, dev*]
    types: [published]

jobs:

  fetch-tag:
    if: github.event.release.target_commitish == 'main' || github.event.release.target_commitish == 'dev'
    name : Get release tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building release tag
        id: latest_tag
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    outputs:
      release_tag: ${{steps.latest_tag.outputs.tag}}

  build-docker-backend:
    name: 'Building the backend docker image'
    runs-on: ubuntu-latest
    needs: [fetch-tag]
    steps:
      - uses: actions/checkout@v2
      - name: Building and tagging the backend docker image
        env:
          IMAGE_TAG: ${{needs.fetch-tag.outputs.release_tag }}
        run: |
          docker build -t mcdapi:$IMAGE_TAG -f env/docker_mcdapi/Dockerfile .

  build-docker-frontend:
    name: 'Building the frontend docker image'
    runs-on: ubuntu-latest
    needs: [fetch-tag]
    steps:
      - uses: actions/checkout@v2
      - name: Building and tagging the frontend docker image
        env:
          IMAGE_TAG: ${{needs.fetch-tag.outputs.release_tag }}
        run: |
          docker build -t mcdui:$IMAGE_TAG -f env/docker_mcdui/Dockerfile .

  build-docker-nginx:
    name: 'Building the nginx docker image'
    runs-on: ubuntu-latest
    needs: [fetch-tag]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: actions/checkout@v2
      - name: Building and tagging the nginx docker image
        env:
          ECR_REGISTRY: 059014103288.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: mcd-discount-staging-nginx
          IMAGE_TAG: ${{needs.fetch-tag.outputs.release_tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f env/docker_nginx/Dockerfile .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
