name: release-workflow

on:
  release:
    branches: [main, dev*]
    types: [published]

jobs:

  fetch-tag:
    if: github.event.release.target_commitish == 'main' || github.event.release.target_commitish == 'dev'
    name : Get release tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building release tag
        id: latest_tag
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
    outputs:
      release_tag: ${{steps.latest_tag.outputs.tag}}

  frontend-img-build:
    name: 'Building frontend docker images'
    runs-on: ubuntu-latest
    needs: [fetch-tag]
    strategy:
      matrix:
        include:
          - ecr_repository: mcd-discount-staging-frontend
            dockerfile_path: env/docker_mcdui/Dockerfile
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: actions/checkout@v2
      - name: Pushing ${{ matrix.ecr_repository }} image to ECR
        env:
          ECR_REGISTRY: 059014103288.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: ${{ matrix.ecr_repository }}
          IMAGE_TAG: ${{needs.fetch-tag.outputs.release_tag }}
          FILE_LOCATION: ${{ matrix.dockerfile_path }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $FILE_LOCATION .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY


  backend-img-build:
    name: 'Building backend docker images'
    runs-on: ubuntu-latest
    needs: [fetch-tag]
    strategy:
      matrix:
        include:
          - ecr_repository: mcd-discount-staging-backend
            dockerfile_path: env/docker_mcdapi/Dockerfile
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: actions/checkout@v2
      - name: Pushing ${{ matrix.ecr_repository }} image to ECR
        env:
          ECR_REGISTRY: 059014103288.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: ${{ matrix.ecr_repository }}
          IMAGE_TAG: ${{needs.fetch-tag.outputs.release_tag }}
          FILE_LOCATION: ${{ matrix.dockerfile_path }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $FILE_LOCATION .
          docker push -a $ECR_REGISTRY/$ECR_REPOSITORY
