name: docker-validation
on:
  pull_request:
    branches: [main, release*, dev*]

jobs:

  frontend-compatibility-check:
    name: frontend-compatibility-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check the frontend docker image
      run: docker build . -f env/docker_mcdui/Dockerfile --tag frontend:latest

  backend-compatibility-check:
    name: docker-compatibility-check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check the backend docker image
      run: docker build . -f env/docker_mcdapi/Dockerfile --tag backend:latest     
